"""Added wallet_address to User

Revision ID: 0baf3f537122
Revises: 
Create Date: 2026-02-28 09:21:15.234929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0baf3f537122'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wallet_address', sa.String(length=42), nullable=True))
        batch_op.create_unique_constraint(None, ['wallet_address'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('wallet_address')

    # ### end Alembic commands ###
