"""AI fields + batch_id string fix

Revision ID: 67f40d75e8dc
Revises: 2a5a04773d52
Create Date: 2026-03-02 01:34:01.858079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67f40d75e8dc'
down_revision = '2a5a04773d52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spinach_batches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('environmental_risk', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('anomaly_detected', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('disease_class', sa.String(length=255), nullable=True))
        batch_op.alter_column('batch_id',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spinach_batches', schema=None) as batch_op:
        batch_op.alter_column('batch_id',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.drop_column('disease_class')
        batch_op.drop_column('anomaly_detected')
        batch_op.drop_column('environmental_risk')

    # ### end Alembic commands ###
