"""Make farmer_address nullable

Revision ID: 6c4aab122b59
Revises: 0baf3f537122
Create Date: 2026-02-28 13:35:37.036460

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6c4aab122b59'
down_revision = '0baf3f537122'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spinach_batches', schema=None) as batch_op:
        batch_op.alter_column('batch_id',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.drop_column('rejection_timestamp')
        batch_op.drop_column('farmer_address')
        batch_op.drop_column('current_owner')
        batch_op.drop_column('storage_timestamp')
        batch_op.drop_column('state')
        batch_op.drop_column('transit_timestamp')
        batch_op.drop_column('cold_chain_violated')
        batch_op.drop_column('delivery_timestamp')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spinach_batches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delivery_timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('cold_chain_violated', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('transit_timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('state', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('storage_timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('current_owner', sa.VARCHAR(length=42), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('farmer_address', sa.VARCHAR(length=42), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('rejection_timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.alter_column('batch_id',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###
